name: Generate official binary repositories

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/repositories.yml'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/repositories.yml'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  postmarketos:
    name: PostmarketOS APK builds
    runs-on: ubuntu-latest

    steps:
      - name: Get repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}
          fetch-depth: 0

      - name: Build packages
        env:
          ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
        run: |
          set -exuo pipefail

          sudo apt-get install python3-pip python3-virtualenv
          virtualenv .
          . bin/activate
          pip3 install tomli
          pip3 install https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/archive/master.tar.gz

          yes '' | pmbootstrap init || true

          sudo rm -rf ~/.local/var/pmbootstrap/config_abuild
          mkdir ~/.local/var/pmbootstrap/config_abuild
          echo "$ABUILD_PRIVATE_KEY" > ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa
          openssl rsa -in ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa -pubout > ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub
          echo 'PACKAGER_PRIVKEY="/home/pmos/.abuild/yukigram.github.io.rsa"' > ~/.local/var/pmbootstrap/config_abuild/abuild.conf
          mkdir -p ~/.local/var/pmbootstrap/config_apk_keys
          sudo cp ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub ~/.local/var/pmbootstrap/config_apk_keys

          pushd "$REPO_NAME"
          pkgver="$(grep ^AppVersionStrSmall Telegram/build/version | grep -o '[0-9].*')"
          pkgrel="$(($(git log | grep ^commit | grep -n $(git blame Telegram/build/version | grep 'AppVersionStrSmall[^)]*$' | cut -d ' ' -f 1-1) | cut -d ':' -f 1-1)-1))"
          popd
          pmbootstrap pull
          pmbootstrap aportgen --fork-alpine telegram-desktop
          ln -s ~/.local/var/pmbootstrap/cache_git/pmaports pmaports
          mv pmaports/temp/telegram-desktop pmaports/temp/yukigram
          cat >> pmaports/temp/yukigram/APKBUILD << EOF

          pkgname=yukigram
          pkgver=$pkgver
          pkgrel=$pkgrel
          pkgdesc="Yukigram (Telegram Desktop fork) messaging app"
          depends="\$depends ada"
          source="\${source/https:*-full.tar.gz/yukigram.tar.gz}"
          builddir="\$srcdir/$REPO_NAME"
          unset maintainer
          EOF

          rm -rf $(find "$REPO_NAME" -name .git)
          tar -czf pmaports/temp/yukigram/yukigram.tar.gz "$REPO_NAME"

          mkdir pmaports/temp/yukigram-key
          cat > pmaports/temp/yukigram-key/APKBUILD << EOF
          pkgname=yukigram-key
          pkgver=1
          pkgrel=0
          pkgdesc="Public key for the Yukigram repository"
          url="https://yukigram.github.io"
          arch="noarch"
          license="MIT"
          source="yukigram.github.io.rsa.pub"
          options="!check"

          package() {
              install -Dm644 "\$srcdir"/yukigram.github.io.rsa.pub "\$pkgdir"/etc/apk/keys/yukigram.github.io.rsa.pub
              install -Dm644 "\$srcdir"/yukigram.github.io.rsa.pub "\$pkgdir"/usr/share/apk/keys/yukigram.github.io.rsa.pub
          }
          EOF
          cp ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub pmaports/temp/yukigram-key/

          pmbootstrap checksum yukigram yukigram-key
          pmbootstrap --details-to-stdout build --arch=x86_64 yukigram
          pmbootstrap --details-to-stdout build --arch=aarch64 yukigram
          pmbootstrap --details-to-stdout build --arch=armv7 yukigram
          pmbootstrap build yukigram-key

          (
            cd ~/.local/var/pmbootstrap
            mkdir pmaports
            mv ~/.local/var/pmbootstrap/cache_git/pmaports/temp/{yukigram,yukigram-key} pmaports/
            tar -cvzf - packages pmaports
          ) > postmarketos-packages.tar.gz

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: postmarketos-packages.tar.gz
          path: postmarketos-packages.tar.gz

  nixos:
    name: NixOS binary cache build
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: nixbuild/nix-quick-install-action@v34
        name: Install Nix

      - name: Build packages
        env:
          NIX_BINARY_CACHE_KEY: ${{ secrets.NIX_BINARY_CACHE_KEY }}
        run: |
          set -exuo pipefail

          FLAKE='(builtins.getFlake "git+https://github.com/${{ github.event.repository.full_name }}?rev=${{ github.sha }}&submodules=1")'
          PKGS="$FLAKE.inputs.nixpkgs.legacyPackages.$(uname -m)-linux"

          nix-build --extra-experimental-features flakes --no-out-link -E "$FLAKE" >/dev/null 2>&1
          nix-build --extra-experimental-features flakes -j 0 --keep-going -E "$FLAKE.packages.$(uname -m)-linux.yukigram" || true
          ls /nix/store | sed 's:^:/nix/store/:' > paths-from-nixos-cache.txt
          nix-build --extra-experimental-features flakes -E "$PKGS.closureInfo { rootPaths = [ $FLAKE.packages.$(uname -m)-linux.yukigram ]; }"

          echo "$NIX_BINARY_CACHE_KEY" > bincache-key.priv
          nix --extra-experimental-features nix-command key convert-secret-to-public < bincache-key.priv > bincache-key.pub

          nix-shell -E "with $PKGS;"' stdenv.mkDerivation { name = "shell"; buildInputs = [ nix-serve ]; }' --run 'NIX_SECRET_KEY_FILE=$PWD/bincache-key.priv nix-serve &'
          while ! curl http://127.0.0.1:5000/; do sleep 1; done

          mkdir -p out/nar
          wget http://127.0.0.1:5000/nix-cache-info -O out/nix-cache-info
          cat paths-from-nixos-cache.txt{,} result/store-paths | sort | uniq -u | sed 's:/nix/store/\([^-]*\)-.*:\1:' | while read path; do
            wget http://127.0.0.1:5000/$path.narinfo -O out/$path.narinfo
            nar="$(grep '^URL: ' out/$path.narinfo | cut -d ' ' -f 2-2)"
            wget http://127.0.0.1:5000/$nar -O out/$nar
          done

          nix-hash --to-base32 "$(nix --extra-experimental-features 'nix-command flakes' eval --raw --expr "$FLAKE.narHash")" > out/narHash
          cp bincache-key.pub out/narPublicKey

          ( cd out; tar -cvzf ../nixos-bincache-$(uname -m).tar.gz .; )
          echo ARCH="$(uname -m)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: nixos-bincache-${{ env.ARCH }}.tar.gz
          path: nixos-bincache-${{ env.ARCH }}.tar.gz

  website:
    name: Website for hosting the repositories
    needs: [postmarketos, nixos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download artifacts

      - name: Prepare website structure
        run: |
          set -exuo pipefail

          mkdir website
          pushd website
          for i in nixos-bincache-x86_64 nixos-bincache-aarch64 postmarketos-packages; do
            tar -xvf ../$i.tar.gz/$i.tar.gz
          done
          popd

          pkgver_pkgrel="$(bash -c '. website/pmaports/yukigram/APKBUILD; echo $pkgver-r$pkgrel')"
          cat > website/index.html << EOF
          <html>
          <head>
          <title>Yukigram builds</title>
          <meta charset="utf-8"/>
          </head>
          <body>
          <h1>Yukigram builds for PostmarketOS</h1>
          <h2>Repository installation (preferred)</h2>
          <p>Run these commands as root to install Yukigram to your PostmarketOS device:</p>
          <pre>wget https://yukigram.github.io/yukigram/pmaports/yukigram-key/yukigram.github.io.rsa.pub -O /etc/apk/keys/yukigram.github.io.rsa.pub
          echo https://yukigram.github.io/yukigram/packages/edge &gt;&gt; /etc/apk/repositories
          apk update
          apk add yukigram yukigram-key
          </pre>
          <h2>Direct APK downloads</h2>
          <p>It is recommended that you add the repository to your device as described above. This way you will get automatic updates. If you still want to install the APK manually, here are the links:</p>
          <ul>
          <li><a href="packages/edge/aarch64/yukigram-$pkgver_pkgrel.apk">aarch64 (64-bit ARMv8)</a></li>
          <li><a href="packages/edge/armv7/yukigram-$pkgver_pkgrel.apk">armv7 (32-bit ARMv7)</a></li>
          <li><a href="packages/edge/x86_64/yukigram-$pkgver_pkgrel.apk">x86_64 (64-bit x86)</a></li>
          <li><a href="pmaports/yukigram/APKBUILD">APKBUILD</a></li>
          </ul>
          <h1>Yukigram builds for NixOS</h1>
          <p>Specify <code>git+https://github.com/${{ github.event.repository.full_name }}?submodules=1</code> as the input URL in your flake.</p>
          <p>Alternatively, you can import the Yukigram package on a non-flake system as follows:</p>
          <pre>callPackage (fetchFromGitHub {
            owner = "yukigram";
            repo = "yukigram";
            rev = "${{ github.sha }}";
            sha256 = "$(cat website/narHash)";
          }) {}</pre>
          <h2>Binary cache</h2>
          <p>To use the binary cache, specify <code>https://yukigram.github.io/yukigram</code> as an extra substituter, and <code>$(cat website/narPublicKey)</code> as an extra trusted key. Note that the binary cache is only provided for the Nixpkgs version pinned in the flake.</p>
          </body>
          </html>
          EOF
          rm -f website/narHash website/narPublicKey

      - uses: actions/upload-pages-artifact@v3.0.1
        name: Upload artifact
        with:
          path: website

      - name: Deploy GitHub Pages site
        if: github.ref == 'refs/heads/dev'
        uses: actions/deploy-pages@v4.0.5
